import React from "react";

const Carousel = () => {
  return (
    <div>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
      <h1>carousel</h1>
    </div>
  );
};

export default Carousel;
